package project.tubespbo.Controllers.SideBar;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.ScrollPane;
import javafx.scene.image.ImageView;
import javafx.scene.layout.AnchorPane;
import project.tubespbo.Models.JurusanModel;
import project.tubespbo.Models.ProdiModel;

import java.net.URL;
import java.util.Arrays;
import java.util.List;
import java.util.ResourceBundle;

public class MajorStudyProgramsController implements Initializable {

    private final List<ProdiModel> daftarProdiJMTI = Arrays.asList(
            new ProdiModel("Matematika", 2, "Program Studi Matematika ITK didirikan berdasarkan Surat Keputusan Dirjen Dikti No. 65/M/Kp/III/2015. Program Studi Matematika berada di dalam Jurusan Matematika dan Teknologi Informasi. Program Studi Matematika telah menyelenggarakan perkuliahan dari tahun 2013 dengan bertempat di Institut Teknologi Sepuluh Nopember, Surabaya, hingga tahun 2014. Mulai pada tahun 2015, Prodi Matematika telah aktif dan mandiri menyelenggarakan pendidikan di kampus ITK, Balikpapan dan telah terakreditasi C sesuai Keputusan Badan Akreditasi Nasional Perguruan Tinggi Nomor 387/SK/BAN-PT/Akred/S/II/2018.\n\nMatematika ITK merupakan program studi yang mempelajari dan mengaplikasikan konsep matematis untuk mengembangkan keilmiahan dan menghasilkan kontribusi dalam bidang sains, teknologi, keuangan, asuransi, lingkungan, kesehatan, ekonomi industri, dan dunia Pendidikan Prodi Matematika memiliki 2 (dua) bidang keahlian yaitu, Matematika Terapan,serta Analisis dan Aljabar."),
            new ProdiModel("Sistem Informasi", 10, "Program Studi Sistem Informasi Institut Teknologi Kalimantan didirikan pada tahun 2015 berdasarkan SK Menteri Riset, Teknologi dan Pendidikan Tinggi No. 65/M/Kp/III/2015. Bersamaan dengan izin penyelenggaraan program studi tersebut, Program Studi Sistem Informasi mulai menerima mahasiswa baru pada tahun 2013 dengan jumlah mahasiswa sebanyak 8 orang. Perkuliahan untuk angkatan pertama ini dilakukan di Program Studi Sistem Informasi Institut Teknologi Sepuluh Nopember (ITS). Pada tahun ajaran 2021/2022 ini, jumlah mahasiswa sudah mencapai 400 orang.  Program studi Sistem Informasi ITK dipimpin oleh koordinator program studi yang mempunyai tugas melaksanakan pengelolaan sumber daya pendukung program studi. Secara lebih rinci, tugas Koordinator Program Studi yang tercantum dalam surat keputusan Rektor adalah memimpin dan mengkoordinasikan kegiatan pendidikan, penelitian, dan pengabdian kepada masyarakat sesuai dengan perundang-undangan yang berlaku. Tata pamong di Institut Teknologi Kalimantan tertuang dalam Statuta ITK tahun 2016 dan OTK ITK Tahun 2015. Sistem dan pelaksanaan tata pamong program studi Sistem Informasi kemudian didasarkan pada OTK ITK yang meliputi prinsip-prinsip kredibilitas, transparansi, akuntabilitas, bertanggungjawab, dan keadilan."),
            new ProdiModel("Informatika", 11, "Program Studi Informatika berdiri pada tahun 2016 bersamaan dengan Program Studi Teknik Industri dan Teknik Lingkungan. Kehadiran program studi Informatika di Institut Teknologi Kalimantan diharapkan dapat berpartisipasi aktif dalam mendukung Buku Putih Indonesia 2005-2025 di bidang Teknologi Informasi dan Komunikasi."),
            new ProdiModel("Statistika", 16, "Program Studi Statistika ITK resmi didirikan atas dasar Surat Keputusan Kementrian Pendidikan dan Kebudayaan Republik Indonesia No. 610/M/2020 pada tanggal 30 Juni 2020. Sebelumnya, statistika merupakan salah satu bidang minat yang ada di Program Studi Matematika. Namun seiring dengan perkembangan kondisi ITK dan menyesuaikan dengan kebutuhan jaman di era big data saat ini, di rasa perlu untuk menjadikan Statistika sebagai Program Studi tersendiri yang ada di lingkungan ITK. Program Studi Statistika berada di bawah Jurusan Matematika dan Teknologi Informasi.\n\nDi dalam Program Studi Statistika, akan dipelajari hal-hal yang berkaitan dengan data, mulai dari  teknik mengumpulkan data, mengolah, menyajikan, menganalisis, dan menginterpretasikan hasil yang diperoleh sebagai dasar dalam pengambilan keputusan yang tepat. Selan itu, di Program Studi Statistika juga akan dipelajari metode-metode dalam memprediksi suatu kejadian di masa mendatang berdasarkan data yang tersedia, sebagai dasar pertimbangan dalam mengantisipasi hal-hal yang akan terjadi dimasa datang.\n\nProgram Studi Statistika ITK berkomitmen untuk menghasilkan lulusan dengan kompetensi yang unggul dan terampil dalam menyelesaikan permasalahan statistik dan big data. Dalam mempersiapkan kompetensi lulusan yang sesuai dengan kebutuhan, Program Studi Statistika ITK menyusun kurikulum pendidikan sedemikian rupa untuk membekali kemampuan mahasiswa di bidang manajemen data dan komputasi. Hal ini tentunya sangat selaras dengan kebutuhan dan perkembangan jaman di era big data dan teknologi. Oleh sebab itu, lulusan dari Program Studi Statistika sangat banyak diperlukan di dunia pekerjaan, baik dari sektor pemerintah, pendidikan, bisnis, dan industri.\n\nDalam proses belajar, mahasiswa akan didampingi oleh para dosen di lingkungan Program Studi Statistika dengan kualifikasi terbaik, lulusan dari Perguruan Tinggi unggul, baik di dalam maupun luar negeri, dengan predikat cumlaude (dengan pujian), sehingga sangat tidak diragukan lagi kemampuan dan kompetensinya dalam menguasai materi dan memberikan pengajaran dengan metode yang mudah dipahami oleh mahasiswa."),
            new ProdiModel("Ilmu Aktuaria", 17, "Program Studi ilmu aktuaria berdiri dengan beberapa pertimbangan diantaranya belum tercukupinya kebutuhan profesi aktuaris di Indonesia, prospek pemindahan Ibu Kota negara yang berimplikasi berpindahnya industri finansial, serta masih rendahnya kesadaran masyarakat terhadap asuransi. Program studi ilmu aktuaria secara resmi berdiri berdasarkan Keputusan Menteri Pendidikan dan Kebudayaan Nomor 610/M/2020 tertanggal 31 Juni 2020. Program studi aktuaria menerima mahasiswa angkatan pertama tahun 2020 melalui jalur mandiri SUMMIT ITK.  Penerimaan melalui jalur SNMPTN dan SBMPTN baru dimulai tahun 2021."),
            new ProdiModel("Bisnis Digital", 20, "Program Bisnis Digital ITK resmi didirikan atas dasar Surat Keputusan Menteri Pendidikan dan Kebudayaan Republik Indonesia No. 145/E/O/2021 Tentang Izin Pembukaan Program Studi Bisnis Digital Program Sarjana pada Institut Teknologi Kalimantan di Kota Balikpapan. Program Studi yang berada di bawah Jurusan Matematika dan Teknologi Informasi ini memulai perkuliahan Angkatan Pertama pada Tahun Ajaran 2021/2022.")
    );

    private final List<ProdiModel> daftarProdiJSTPK = Arrays.asList(
            new ProdiModel("Fisika", 1, "Fisika ITK merupakan salah satu program studi yang berbasis sains dasar (basic science). Fisika ITK didirikan pada tahun 2013 bersama dengan lima program studi yang lain ketika ITK masih dalam asuhan Institut Teknologi Sepuluh Nopember (ITS) dan diresmikan sesuai dengan SK Dirjen Dikti No.65/M/Kp/III/2015. Pada tahun 2013, seluruh mahasiswa Fisika ITK dititipkan di ITS khususnya di program studi Fisika. Tepat pada bulan Agustus 2015, seluruh proses belajar mengajar Fisika dipindahkan ke Balikpapan.\n"),
            new ProdiModel("Teknik Kelautan", 14, "Pedoman pembukaan dan penutupan program studi mengacu pada SK Dirjen Dikti Nomor 108/DIKTI/Kep/2001 tentang Pedoman Pembukaan Program Studi dan/atau Jurusan Berdasarkan Keputusan Menteri Pendidikan Nasional Nomor 234/U/2000 tentang Pendirian Perguruan Tinggi. Keputusan Senat ITK tentang pembukaan program studi baru guna memenuhi kebutuhan tenaga ahli bidang teknologi serta dalam upaya pengembangan Tri Dharma Pendidikan ITK khususnya dibidang pendidikan, maka dipandang perlu membuka program studi baru. Hasil Senat ITK pada tanggal 26 Januari 2017 memutuskan dan menetapkan pembukaan program studi baru, yaitu program studi Teknik Kelautan.\n\nBerdasarkan Keputusan Menteri Riset, Teknologi, dan Pendidikan Tinggi Republik Indonesia, Nomor 338/KPT/I/2017 memutuskan Keputusan Menteri Riset, Teknologi, dan Pendidikan Tinggi Republik Indonesia tentang Izin Pembukaan Program Studi Teknik Kelautan Program Sarjana pada Institut Teknologi Kalimantan di Balikpapan."),
            new ProdiModel("Teknologi Pangan", 19, "Program Studi Teknologi Pangan ITK secara resmi berdiri pada 5 April 2021 sesuai SK Menteri Pendididkan dan Kebudayaan Republik Indonesia No 89/E/O/III/2021. Teknologi Pangan ITK telah menerima mahasiswa pertamanya pada tahun 2021.  Saat ini Teknologi Pangan ITK memiliki akreditasi Baik sesuai dengan 14172/SK/BAN-PT/PB-PS/S/III/2022. Lambatnya perkembangan industri pangan di Kalimantan ditandai dengan beberapa industri saja yang mau berinvestasi di Kalimantan. Program Studi Teknologi Pangan hadir dengan harapan iklim perkembangan industri pangan di tengah rencana IKN baru menjadi lebih terarah. Banyak potensi alam Kalimantan yang belum tereksploitasi dengan sangat baik, khususnya palawija, buah tropik, dan kekayaan laut khas Kalimantan. Dengan berkembangnya Program Studi Teknologi Pangan kami bercita-cita untuk menghasilkan terobosan-terobosan baru di pengolahan pangan."),
            new ProdiModel("Teknik Perkapalan", 9, "Pendirian program studi Teknik Perkapalan bersamaan dengan pendirian Institut Teknologi Kalimantan. Pelaksanaan strategi utama dalam bidang penguatan kemampuan Sumber Daya Manusia (SDM) serta Ilmu Pengetahuan dan Teknologi (IPTEK) nasional di Koridor Ekonomi Kalimantan berada pada Masterplan Percepatan dan Perluasan Pembangunan Ekonomi Indonesia (MP3EI) 2011-2025. Program studi Teknik Perkapalan memulai proses perkuliahan pada tahun 2012, sebanyak 20 mahasiswa dengan Jalur penerimaan mahasiswa melalui Seleksi Masuk ITK (SMITeK). SMITeK merupakan hasil kerjasama antara Institut Teknologi Sepuluh Nopember (ITS) Surabaya dengan Pemerintah Provinsi Kalimantan Timur (dengan beasiswa Kaltim Cemerlang). Pada tahun 2013, SMITeK membuka jalur mandiri nasional untuk calon mahasiswa yang berasal dari luar. Sedangkan pada tahun 2014 SMITek diselenggarakan melalui 2 jalur, yaitu: Seleksi Lokal Berbeasiswa Pemprov Kaltim dan Seleksi Bersama Masuk Perguruan Tinggi Negeri (SBMPTN). Pada tahun ini pula ITK diresmikan sebagai PTN oleh Presiden Susilo Bambang Yudhoyono.\n\nSebelumnya program studi Teknik Perkapalan melakukan kegiatan akademik dan proses perkuliahan di kampus ITS Surabaya. Pada tahun 2015, kegiatan akademik dan proses perkuliahan dari total 31 mahasiswa dipindahkan ke Kampus ITK Karangjoang, Balikpapan. Momen ini juga sebagai penerbitan SK pendirian program studi Teknik Perkapalan ITK.")
    );

    private final List<ProdiModel> daftarProdiJTIP = Arrays.asList(
            new ProdiModel("Rekayasa Keselamatan", 18, "Program Studi Rekayasa Keselamatan diresmikan pada tanggal 5 April 2021  SK Menteri Pendididkan dan Kebudayaan Republik Indonesia No 89/E/O/III/2021.\n\nAlasan berdirinya program studi Rekayasa Keselamatan dikarenakan sampai saat ini, belum ada institusi baik negeri maupun swasta di Indonesia yang menawarkan program pendidikan sarjana Rekayasa Keselamatan. Hal ini didukung yang secara nasional jumlah kasus kecelakaan kerja mengalami peningkatan setiap tahunnya serta kebutuhan tenaga ahli keselamatan dan kesehatan kerja yang masih kurang khususnya di daerah Kalimantan. Selain itu, sebagaimana tertuang dalam rencana jangka panjang strategis nasional, ibukota negara akan dipindahkan ke Kalimantan Timur. Sehingga sebagai satu-satunya kampus teknik di Kalimantan, ITK akan menjadi mitra strategis bagi pembangunan ibukota negara baru. Tantangan lain akan muncul yaitu bagaimana lulusan-lulusan Program Studi Rekayasa Keselamatan ITK dapat menjadi kontributor aktif dalam pembangunan ibukota yang bebas dari kecelakaan kerja.\n\nKeunikan yang ada dalam Program Studi Rekayasa Keselamatan (PSRK) adalah adanya perkembangan keilmuan di bidang keselamatan kerja yang dulunya berfokus hanya pada personal safety, namun sejak tahun 2010 mulai berkembang pada keilmuan proses safety yang saat ini mulai menjadi perhatian perusahaan dunia dalam menjamin lingkungan yang aman. Sehingga, hal ini menjadi suatu tantangan tersendiri bagi PSRK ITK untuk menjawab lulusan-lulusan seperti apa kemudian yang dibutuhkan terutama bagi perusahaan-perusahaan di Kalimantan dalam melakukan rekayasa keselamatan untuk menciptakan zero accident. Sehingga prodi Rekayasa Keselamatan ITK memposisikan diri untuk fokus pada konsep process safety  dalam rangka pengendalian resiko yang ada dilingkungan kerja serta memberikan skill dan pengetahuan yang penting dalam melakukan persiapan, pelaksanaan, monitoring dan evaluasi serta peningkatan sistem manajemen keselamatan dan kesehatan kerja. "),
            new ProdiModel("Teknik Elektro", 4, "Prodi Teknik Elektro Berdiri pada 14 Februari 2014 yang diusulkan oleh Jurusan Teknik Elektro Institut Teknologi Sepuluh Nopember (ITS) . Prodi teknik elektro diinisiasi untuk menghasilkan SDM dalam bidang teknik untuk memenuhi kebutuhan industri yang ada di Kalimantan Timur. Program Studi Teknik Elektro ITK menerima angkatan pertama sebanyak 20 mahasiswa. Jalur penerimaan mahasiswa ITK melalui Jalur Seleksi Masuk ITK (SMITeK) yang merupakan hasil kerjasama Institut Teknologi Sepuluh Nopember (ITS) Surabaya dengan Pemerintah Provinsi Kalimantan Timur, melalui beasiswa Kaltim Cemerlang. Proses kuliah pada awal inisiasi diadakan di Institut Teknologi Sepuluh Nopember sembari menunggu persiapan pembangunan gedung."),
            new ProdiModel("Teknik Industri", 12, "Prodi Studi Teknik Industri dibuka berdasarkan hasil keputusan Senat ITK pada tanggal 26 Januari 2017 yang berisi tentang pembukaan program studi baru guna memenuhi kebutuhan tenaga ahli bidang teknologi serta dalam upaya pengembangan Tri Dharma Pendidikan ITK khususnya dibidang pendidikan, maka dipandang perlu membuka program studi baru. Sehingga disusunlah pembukaan program studi teknik industri yang mengacu pada SK Dirjen Dikti Nomor 108/DIKTI/Kep/2001 tentang Pedoman Pembukaan Program Studi dan/atau Jurusan Berdasarkan Keputusan Menteri Pendidikan Nasional Nomor 234/U/2000 tentang Pendirian Perguruan Tinggi serta melibatkan pakar Teknik Industri seperti Dr. Ir. Sri Gunani Pratiwi (ITS), Ir. Sritomo Wignjosoebroto, M.Sc (ITS) dan Prof. Ir. Budi Santosa, MS, PhD (ITS) agar memperoleh masukan terkait kondisi terkini dibidang Teknik Industri.\n\nBerdasarkan Surat Keputusan Menteri Riset, Teknologi, dan Pendidikan Tinggi Repoblik Indonesia No.209/KPT/I/2017, tanggal 4 April 2017 tentang izin pembukaan Program Studi Teknik Indsutri Program Sarjana pada Institut Teknologi Kalimantan."),
            new ProdiModel("Teknik Kimia", 5, "Teknik kimia merupakan program studi yang mempelajari pemrosesan bahan mentah menjadi produk yang bernilai tambah, baik produk jadi maupun produk setengah jadi dengan menerapkan prinsip kimia, fisika, biologi dengan memperhatikan faktor keamanan, lingkungan dan ekonomis.\n\nProgram Studi Teknik Kimia (PSTK) ITK sendiri resmi didirikan pada tahun 2015 sesuai SK Menteri Riset, Teknolgi, dan Pendidikan Tiggi no 65/M/Kp/III/2015.bersama 4 (empat) prodi pertama ITK lainnya. Hanya saja PSTK telah menerima mahasiswa pertamanya pada tahun 2012 dimana seluruh kegiatan perkuliahan dilaksanakan di Jurusan Teknik Kimia ITS, kampus yang ditunjuk oleh Kementerian Ristekdikti sebagai Pelaksana pendirian ITK. Pendirian ITK dan PSTK ini diharapkan mamapu menjawab tantangan pengembangan SDM di Indonesia Timur khususnya sehingga mampu berkontribusi aktif dalam perkembangan dan pembangunan daerah khususnya di Kalimantan."),
            new ProdiModel("Teknik Logistik", 21, "Teknik Logistik merupakan program studi yang mempelajari tentang cara untuk mengatur dan mengontrol arus barang, energi, informasi, dan sumber daya lainnya dari titik supply ke titik konsumsi dengan tujuan mengoptimalkan dan mengefisiensikan penggunaan modal. Logistik juga mencakup integrasi informasi (smart logistic), pergudangan, reverse logistics dan pemaketan.\nProgram Studi Teknik Logistik ITK sendiri resmi didirikan pada tahun 2021 sesuai SK Menteri Pendidikan, Kebudayaan, Riset, dan Teknologi Direktorat Jenderal Pendidikan Tinggi nomor 6320/E1/TP.01.06/2021 seusai proses seleksi mandiri di ITK telah ditutup. Sehingga proses penerimaan mahasiswa baru Teknik Logistik baru akan dibuka pada tahun 2022 mengikuti proses seleksi SNMPTN, SBMPTN, dan jalur Mandiri (Summit ITK). Pendirian Program Studi Teknik Logistik ini diharapkan mampu menjawab tantangan pengembangan SDM di Indonesia Timur khususnya sehingga mampu berkontribusi aktif dalam perkembangan dan pembangunan daerah khususnya di Kalimantan."),
            new ProdiModel("Teknik Mesin", 3, "Program Studi Teknik Mesin merupakan salah satu program studi tertua di ITK. Program Studi Teknik Mesin ITK didirikan pada tahun 2012 dengan jumlah mahasiswa sebanyak 20 mahasiswa yang berasal dari Kalimantan. Jalur penerimaan mahasiswa ITK pada saat itu dilakukan melalui Seleksi Masuk ITK (SMITeK) yang merupakan hasil kerjasama antara ITS dan Pemprov Kaltim. Seluruh mahasiswa berasal dari Provinsi Kaltim mendapatkan beasiswa Kaltim Cemerlang.  Kegiatan perkuliaahan pada tahun pertama sampai tahun ketiga dilaksanakan di kampus ITS. Pada tahun 2015 semua kegiatan akademik dan non akademik sudah dilaksanakan di kampus ITK di Karang Joang Balikpapan. Untuk mencetak lulusan Teknik Mesin ITK yang berkualitas, telah disusun kurikulum pengajaran yang memberikan dasar ilmu pengetahuan dan teknik yang kuat serta implementasi dalam bidang keteknikan sehingga lulusan Teknik Mesin ITK juga harus mampu bersaing di dunia kerja.")
    );

    private final List<ProdiModel> daftarProdiJTSP = Arrays.asList(
            new ProdiModel("Arsitektur",15, "Institut Teknologi Kalimantan (ITK) merupakan perguruan tinggi yang fokus dalam bidang teknologi untuk menunjang kebutuhan dunia industri. ITK memulai proses perkuliahan pada tahun 2012 dan menerima mahasiswa angkatan pertama sebanyak 100 mahasiswa. 5 program studi awal saat ITK berdiri yaitu: Teknik Elektro, Teknik Mesin, Teknik Perkapalan, Teknik Kimia dan Teknik Sipil. Jalur penerimaan mahasiswa ITK tersebut dilakukan melalui Seleksi Masuk ITK (SMITeK) yang merupakan hasil kerjasama antara Institut Teknologi Sepuluh Nopember (ITS) Surabaya dengan Pemerintah Propinsi Kalimantan Timur, melalui beasiswa Kaltim Cemerlang. Pada tahun 2013, ITK menyelenggarakan SMITeK dengan membuka jalur mandiri nasional untuk calon mahasiswa yang berasal dari luar Kaltim. Selain itu, juga dibuka lima program studi baru, yaitu program studi Teknik Material dan Metalurgi, Fisika, Matematika, Sistem Informasi, dan Perencanaan Wilayah dan Kota. SMITek pada tahun 2014 diselenggarakan melalui 2 jalur, yaitu Seleksi Lokal Berbeasiswa Pemprov Kaltim dan Seleksi Bersama Masuk Perguruan Tinggi Negeri (SBMPTN). Pada tahun ini pula ITK diresmikan sebagai PTN oleh Presiden Susilo Bambang Yudhoyono. Dari tahun 2012 sampai dengan tahun 2014, ITK memiliki total mahasiswa sebanyak 263 mahasiswa yang melakukan kegiatan akademik dan proses perkuliahan di kampus ITS Surabaya. Pada tahun 2015, kegiatan akademik dan proses perkuliahan dipindahkan di Kampus ITK Karangjoang, Balikpapan."),
            new ProdiModel("Desain Komunikasi Visual",22, "Program Studi Desain Komunikasi Visual didirikan pada tahun 2022 dengan NOMOR : 4653/SK/BAN-PT/Ak.P/S/VII/2022 sebagai salah satu Program Studi di Institut Teknologi Kalimantan sebagai salah satu program studi di bawah Jurusan Teknik Sipil Dan Perencanaan. Koordinator Program Studi pertama adalah Olivia Febrianty Ngabito M.Sn. Jumlah Dosen dari DKV Berjumlah 9 Orang. Program Studi Desain Komunikasi Visual di Institut Teknologi Kalimantan Merupakan Jurusan Desain Komunikasi Visual pertama di pulau Kalimantan. Hal ini merespon dari berkembangnya industri desain di kalimantan terutama Kota Balikpapan dengan Konsep Smart City."),
            new ProdiModel("Perencanaan Wilayah dan Kota",8, "Institut Teknologi Kalimantan memulai proses perkuliahan pada tahun 2012. Pada tahun tersebut, ITK menerima mahasiswa angkatan pertama sebanyak 100 mahasiswa dan didistribusikan ke 5 program studi awal ITK, yaitu: Teknik Elektro, Teknik Mesin, Teknik Perkapalan, Teknik Kimia dan Teknik Sipil. Jalur penerimaan mahasiswa ITK tersebut dilakukan melalui Seleksi Masuk ITK (SMITeK) yang merupakan hasil kerjasama antara Institut Teknologi Sepuluh Nopember (ITS) Surabaya dengan Pemerintah Propinsi Kalimantan Timur, melalui beasiswa Kaltim Cemerlang.\nPermasalahan tata ruang (spasial) yang semakin dinamis disamping tuntutan akan pembangunan ekonomi yang berkelanjutan meningkatkan kebutuhan akan sarjana unggul bidang perencanaan wilayah dan kota. Oleh karena itu, Institut Teknologi Kalimantan membuka Program Studi Perencanaan Wilayah dan Kota (PWK) mulai tahun 2013. Melalui jalur SMITek dengan membuka jalur mandiri nasional untuk calon mahasiswa baru, ITK menerima mahasiswa Prodi PWK bersamaan dengan 4 prodi lainnya yang baru dibuka seperti Teknik Material dan Metalurgi, Fisika, Matematika, dan Sistem Informasi. Program studi ini menfokuskan diri pada studi perencanaan, perancangan, pemanfaatan, pengelolaan, dan pengendalian ruang kota, wilayah, dan pesisir yang terpadu. Pada tahun 2013, PWK mendapatkan 12 mahasiswa yang merupakan putra-putri Kalimantan Timur dengan didukung oleh beasiswa Kaltim Cemerlang.\n\nPada tahun 2014, SMITeK diselenggarakan lagi melalui 2 jalur, yaitu Seleksi Lokal Berbeasiswa Pemprov Kaltim Cemerlang dan Seleksi Bersama Masuk Perguruan Tinggi Negeri (SBMPTN). Pada tahun ini pula ITK diresmikan sebagai PTN oleh Presiden Susilo Bambang Yudhoyono. Dari tahun 2012 sampai dengan tahun 2014, ITK memiliki total mahasiswa sebanyak 263 mahasiswa yang melakukan kegiatan akademik dan proses perkuliahan di kampus ITS Surabaya. Pada tahun 2015, kegiatan akademik dan proses perkuliahan dipindahkan ke Kampus ITK Karang Joang, Balikpapan."),
            new ProdiModel("Teknik Sipil",7, "Program Studi S1 Teknik Sipil Jurusan Teknik Sipil dan Perencanaan Institut Teknologi Kalimantan lahir bersama-sama dengan pendirian Institut Teknologi Kalimantan. Riwayat pendirian Institut Teknologi Kalimantan didasarkan pada pelaksanaan strategi utama dalam bidang kemampuan Sumber Daya Manusia (SDM) serta Ilmu Pengetahuan dan Teknologi (IPTEK) nasional di Koridor Ekonomi Kalimantan semagaimana yang disusun dalam Masterplan Percepatan dan Perluasan Pembangunan Ekonomi Indonesia (MP3EI) 2011-2025. Selain Politeknik, hingga tahun 2012 Kalimantan Timur hanya memiliki satu universitas negeri yaitu Universitas Mulawarman yang berada di Samarinda. Menginat kekayaan Sumber Daya Alam (SDA) dan pertambahan penduduk yang terus meningkat, maka penambahan Perguruan Tinggi Negeri (PTN) sangat diperlukan utuk mendukung perkembangan dan pembangunan daerah khusunya Kalimantan.\n\nProgram Studi Teknik Sipil ITK didirikan bersama 4 program studi lain yakni Teknik Elektro, Teknik Mesin, Teknik Perkapalan, dan Teknik Kimia yang merupakan program studi rintisan. Program Studi Teknik Sipil ITK memulai perkuliahan sejak awal berdiri hingga tahun 2014 di kampus ITS Surabaya. Pada tahun 2015 kegiatan akademik dan proses perkuliahan dipindahkan di Kampus ITK Karang Joang, Balikpapan.")
    );

    private final List<ProdiModel> daftarProdiJIKL = Arrays.asList(
            new ProdiModel("Teknik Lingkungan",13, "Program Studi Teknik Lingkungan merupakan program studi ke-13 yang berdiri di Institut Teknologi Kalimantan. Proses pendirian Program Studi Teknik Lingkungan dibantu oleh Dosen Program Studi Teknik Sipil di bawah arahan Dr. Ir. Elina Sitepu Pandebesie, M.T., yang kemudian dilanjutkan oleh 5 orang Dosen Program Studi Teknik Lingkungan yang diterima di ITK pada Januari 2016. Pengajuan program studi ini telah dilakukan sejak bulan Maret 2016, sebelum akhirnya resmi terbentuk dengan ditandai penerbitan Keputusan Menteri Riset, Teknologi, dan Pendidikan Tinggi RI Nomor 285/KPT/I/2017 Tentang Izin Pembukaan Program Studi Teknik Lingkungan Program Sarjana pada Institut Teknologi Kalimantan pada tanggal 29 Mei 2017. Dengan terbitnya izin pendirian prodi, Program Studi Teknik Lingkungan melakukan proses penjaringan mahasiswa melalui Seleksi Mandiri tahun 2017. Melalui seleksi tersebut, secara resmi 10 mahasiswa angkatan pertama diterima pada Program Studi ini dibawah arahan Koordinator Program Studi Teknik Lingkungan periode Juni – Agustus 2018, M. Ma’arij Harfadli, S.T., M.T. Selanjutnya sejak September 2018 hingga saat ini, posisi Koordinator Program Studi Teknik Lingkungan dipegang oleh Umi Sholikah, S.Si., M.T."),
            new ProdiModel("Teknik Material dan Metalurgi",6, "Program Studi Teknik Material dan Metalurgi didirikan pada tahun 2013 sebagai salah satu Program Studi di Institut Teknologi Kalimantan sebagai salah satu program studi di bawah Jurusan Ilmu Kebumian dan Lingkungan. Koordinator Program Studi pertama adalah Yunita Triana, S.Si. M.Si dengan jumlah mahasiswa angkatan 2013 sebanyak 11 orang. Namun, kegiatan akademik belum berjalan optimal karena gedung perkuliahan di Balikpapan masih dalam masa pembangunan, keterbatasan pengajar di bidang Material dan Metalurgi dan fasilitas laboraturium, sehingga pada saat itu mahasiswa dititipkan di Institut Teknologi Sepuluh Nopember (ITS) hingga tahun 2015. Secara resmi, Program Studi Teknik Material dan Metalurgi memiliki izin pendirian berdasarkan SK Dirjen Dikti 65/M/Kp/III/2015 tertanggal 20 Maret 2015 yang ditandatangani oleh Bapak Patdono Suwignjo. Hingga tahun 2018, Perkembangan jumlah penerimaan mahasiswa pada tahun 2014 sebanyak 9 orang, angkatan tahun 2015 sebanyak 46, angkatan 2016 sebanyak 79, angkatan 2017 sebanyak 82 orang, dan 2018 sebanyak 86 orang. Sejak saat itu, kegiatan belajar mengajar berjalan secara kontinu dan konsisten dengan jumlah rata-rata mahasiswa baru sebesar 80 orang. Pada tahun 2018 Teknik Material dan Metalurgi terakreditasi B berdasarkan keputusan BAN-PT No.859/K/BAN-PT/ Akred/S/III/2018.")
    );

    private final JurusanModel JMTI = new JurusanModel(
            "Jurusan Matematika dan Teknologi Informasi",
            "Jurusan Matematika dan Teknologi Informasi (JMTI) sebagai salah satu dari lima jurusan yang ada di Institut Teknologi Kalimantan yang didirikan pada tahun 2015. JMTI merupakan jurusan terbesar yang memiliki lima program studi yaitu, Matematika, Sistem Informasi, Informatika, Statistika, dan Ilmu Aktuaria dengan jumlah keseluruhan 803 mahasiswa. Pada tahun 2021, JMTI menginisiasi pendirian program studi baru Bisnis Digital. Saat ini, JMTI ITK memiliki 44 dosen tetap, dengan 10 dosen Asisten Ahli dan 3 dosen sedang melaksanakan studi lanjut program doctor di kampus dalam negeri dan luar negeri.",
                daftarProdiJMTI
    );
    private final JurusanModel JSTPK = new JurusanModel(
            "Jurusan Sains, Teknologi Pangan, dan Kemaritiman",
            "Jurusan Sains, Teknologi Pangan, dan Kemaritiman (JSTPK) sebagai salah satu jurusan di Institut Teknologi Kalimantan yang didirikan pada tahun 2015. JSTPK memiliki 4 program studi yaitu, Fisika, Teknik Perkapalan, Teknik Kelautan dan Teknologi Pangan. Saat ini, JSTPK memiliki 36 dosen dimana 3 dosen sedang melakukan studi lanjut program doctor di UK, Australia, dan Surabaya. Selain dosen, JSTPK juga disupport dengan tenaga kependidikan dan laboran.",
            daftarProdiJSTPK
    );
    private final JurusanModel JTIP = new JurusanModel(
            "Jurusan Teknologi Industri dan Proses",
            "Jurusan Teknologi Industri dan Proses (JTIP) telah berusia 4 Tahun, yang didirikan pada tahun 2018. JTIP merupakan satu diantara 5 Jurusan yang ada di Institut Teknologi Kalimantan. Terdapat 3 rumpun laboratorium pendukung di JTIP. Laboratorium tersebut dibagi berdasarkan bidang peminatan berupa Program Studi yang ada di JTIP, yaitu Program Studi Teknik Mesin, Teknik Elektro, Teknik Kimia, Teknik Industri, Rekayasa Keselamatan, dan Teknik Logistik. Di antara 6 (enam) Program Studi di JTIP, terdapat 3 program studi yang telah melakukan akreditasi internasional ASIIN dan 3 mendapatkan akreditasi nasional.",
            daftarProdiJTIP
    );
    private final JurusanModel JTSP = new JurusanModel(
            "Jurusan Teknik Sipil dan Perencanaan",
            "Jurusan Teknik Sipil dan Perencanaan (JTSP) adalah satu dari lima Jurusan yang dimiliki oleh Institut Teknologi Kalimantan (ITK). Diresmikan bersama dengan berdirinya ITK pada tahun 2014, saat ini usia JTSP telah memasuki usia yang ke 6, tepatnya pada tanggal 6 Oktober 2020. JTSP memiliki 4 program studi yaitu Program Studi S1 Teknik Sipil, Program Studi S1 Perencanaan Wilayah dan Kota, Program Studi S1 Arsitektur, dan Program Studi S1 Desain Komunikasi Visual. Dalam menunjang kegiatan akademik baik pendidikan, penelitian dan pengabdian masyarakat sampai dengan saat ini JTSP telah memiliki 40 dosen tetap dengan latar belakang pendidikan Magister (S2) dan Doktoral (S3) lulusan dari perguruan tinggi dalam dan luar negeri. Saat ini, JTSP dipimpin oleh seorang Ketua Jurusan (Kajur) bersama 3 orang Koordinator Program Studi (Korprodi) dan 3 orang Kepala Laboratorium (Kalab).",
            daftarProdiJTSP
    );
    private final JurusanModel JIKL = new JurusanModel(
            "Jurusan Ilmu Kebumian dan Lingkungan",
            "Jurusan Ilmu Kebumian dan Lingkungan (JIKL) merupakan jurusan yang terdiri dari 2 program studi yaitu Teknik Lingkungan dan Teknik Material dan Metalurgi. Pada Maret 2023, jumlah dosen dan tenaga kependidikan di JIKL ITK terdiri dari 30 orang, dengan rincian 15 orang di Program Studi Teknik Lingkungan (TL), 12 orang di Teknik Material dan Metalurgi (TMM), 2 orang tenaga kependidikan akademik, serta 1 orang tenaga kependidikan keuangan. Dari total 30 orang, terdapat 3 dosen TMM dan 3 dosen TL yang berstatus nonaktif karena sedang menempuh tugas belajar.",
            daftarProdiJIKL
    );

    @FXML
    private AnchorPane paneContainer;

    @FXML
    private ScrollPane prodiInformationPane;

    @FXML
    private ImageView imageProdi;

    @FXML
    private Label headingLabel, namaProdiLabel, nomorProdiLabel, deskripsiProdiLabel, namaJMTI, namaJSTPK, namaJTIP, namaJTSP, namaJIKL, deskripsiJMTI, deskripsiJSTPK, deskripsiJTIP, deskripsiJTSP, deskripsiJIKL;

    @FXML
    private Button backButton, badges, buttonBisnisDigital, buttonIlmuAktuaria, buttonInformatika, buttonMatematika, buttonSistemInformasi, buttonStatistika, buttonFisika, buttonTeknikKelautan, buttonTeknologiPangan, buttonTeknikPerkapalan, buttonRekayasaKeselamatan,buttonTeknikElektro, buttonTeknikIndustri, buttonTeknikKimia, buttonTeknikLogistik, buttonTeknikMesin, buttonArsitektur, buttonDesainKomunikasiVisual, buttonPerencanaanWilayahdanKota, buttonTeknikSipil, buttonTeknikLingkungan, buttonTeknikMaterialdanMetalurgi;

    @Override
    public void initialize(URL url, ResourceBundle resourceBundle) {
        initializeJurusanLabels();
        initializeProdiButton();
    }

    private void initializeJurusanLabels() {
        setJurusanLabel(namaJMTI, deskripsiJMTI, JMTI);
        setJurusanLabel(namaJSTPK, deskripsiJSTPK, JSTPK);
        setJurusanLabel(namaJTIP, deskripsiJTIP, JTIP);
        setJurusanLabel(namaJTSP, deskripsiJTSP, JTSP);
        setJurusanLabel(namaJIKL, deskripsiJIKL, JIKL);
    }

    private void setJurusanLabel(Label namaLabel, Label deskripsiLabel, JurusanModel jurusan) {
        namaLabel.setText(jurusan.getNama());
        deskripsiLabel.setText(jurusan.getDeskripsi());
    }

    private void initializeProdiButton() {
        List<Button> buttons = Arrays.asList(
                buttonBisnisDigital, buttonIlmuAktuaria, buttonInformatika,
                buttonMatematika, buttonSistemInformasi, buttonStatistika, buttonFisika, buttonTeknikKelautan,
                buttonTeknologiPangan, buttonTeknikPerkapalan, buttonRekayasaKeselamatan, buttonTeknikElektro, buttonTeknikIndustri,
                buttonTeknikKimia, buttonTeknikLogistik, buttonTeknikMesin, buttonArsitektur, buttonDesainKomunikasiVisual,
                buttonPerencanaanWilayahdanKota, buttonTeknikSipil, buttonTeknikLingkungan, buttonTeknikMaterialdanMetalurgi
        );

        List<ProdiModel> prodiModels = Arrays.asList(
                new ProdiModel("Bisnis Digital", 20, "Program Bisnis Digital ITK resmi didirikan atas dasar Surat Keputusan Menteri Pendidikan dan Kebudayaan Republik Indonesia No. 145/E/O/2021 Tentang Izin Pembukaan Program Studi Bisnis Digital Program Sarjana pada Institut Teknologi Kalimantan di Kota Balikpapan. Program Studi yang berada di bawah Jurusan Matematika dan Teknologi Informasi ini memulai perkuliahan Angkatan Pertama pada Tahun Ajaran 2021/2022."),
                new ProdiModel("Ilmu Aktuaria", 17, "Program Studi ilmu aktuaria berdiri dengan beberapa pertimbangan diantaranya belum tercukupinya kebutuhan profesi aktuaris di Indonesia, prospek pemindahan Ibu Kota negara yang berimplikasi berpindahnya industri finansial, serta masih rendahnya kesadaran masyarakat terhadap asuransi. Program studi ilmu aktuaria secara resmi berdiri berdasarkan Keputusan Menteri Pendidikan dan Kebudayaan Nomor 610/M/2020 tertanggal 31 Juni 2020. Program studi aktuaria menerima mahasiswa angkatan pertama tahun 2020 melalui jalur mandiri SUMMIT ITK.  Penerimaan melalui jalur SNMPTN dan SBMPTN baru dimulai tahun 2021."),
                new ProdiModel("Informatika", 11, "Program Studi Informatika berdiri pada tahun 2016 bersamaan dengan Program Studi Teknik Industri dan Teknik Lingkungan. Kehadiran program studi Informatika di Institut Teknologi Kalimantan diharapkan dapat berpartisipasi aktif dalam mendukung Buku Putih Indonesia 2005-2025 di bidang Teknologi Informasi dan Komunikasi."),
                new ProdiModel("Matematika", 2, "Program Studi Matematika ITK didirikan berdasarkan Surat Keputusan Dirjen Dikti No. 65/M/Kp/III/2015. Program Studi Matematika berada di dalam Jurusan Matematika dan Teknologi Informasi. Program Studi Matematika telah menyelenggarakan perkuliahan dari tahun 2013 dengan bertempat di Institut Teknologi Sepuluh Nopember, Surabaya, hingga tahun 2014. Mulai pada tahun 2015, Prodi Matematika telah aktif dan mandiri menyelenggarakan pendidikan di kampus ITK, Balikpapan dan telah terakreditasi C sesuai Keputusan Badan Akreditasi Nasional Perguruan Tinggi Nomor 387/SK/BAN-PT/Akred/S/II/2018.\n" +
                        "\n" +
                "Matematika ITK merupakan program studi yang mempelajari dan mengaplikasikan konsep matematis untuk mengembangkan keilmiahan dan menghasilkan kontribusi dalam bidang sains, teknologi, keuangan, asuransi, lingkungan, kesehatan, ekonomi industri, dan dunia Pendidikan Prodi Matematika memiliki 2 (dua) bidang keahlian yaitu, Matematika Terapan,serta Analisis dan Aljabar."),
                new ProdiModel("Sistem Informasi", 10, "Program Studi Sistem Informasi Institut Teknologi Kalimantan didirikan pada tahun 2015 berdasarkan SK Menteri Riset, Teknologi dan Pendidikan Tinggi No. 65/M/Kp/III/2015. Bersamaan dengan izin penyelenggaraan program studi tersebut, Program Studi Sistem Informasi mulai menerima mahasiswa baru pada tahun 2013 dengan jumlah mahasiswa sebanyak 8 orang. Perkuliahan untuk angkatan pertama ini dilakukan di Program Studi Sistem Informasi Institut Teknologi Sepuluh Nopember (ITS). Pada tahun ajaran 2021/2022 ini, jumlah mahasiswa sudah mencapai 400 orang.  Program studi Sistem Informasi ITK dipimpin oleh koordinator program studi yang mempunyai tugas melaksanakan pengelolaan sumber daya pendukung program studi. Secara lebih rinci, tugas Koordinator Program Studi yang tercantum dalam surat keputusan Rektor adalah memimpin dan mengkoordinasikan kegiatan pendidikan, penelitian, dan pengabdian kepada masyarakat sesuai dengan perundang-undangan yang berlaku. Tata pamong di Institut Teknologi Kalimantan tertuang dalam Statuta ITK tahun 2016 dan OTK ITK Tahun 2015. Sistem dan pelaksanaan tata pamong program studi Sistem Informasi kemudian didasarkan pada OTK ITK yang meliputi prinsip-prinsip kredibilitas, transparansi, akuntabilitas, bertanggungjawab, dan keadilan."),
                new ProdiModel("Statistika", 16, "Program Studi Statistika ITK resmi didirikan atas dasar Surat Keputusan Kementrian Pendidikan dan Kebudayaan Republik Indonesia No. 610/M/2020 pada tanggal 30 Juni 2020. Sebelumnya, statistika merupakan salah satu bidang minat yang ada di Program Studi Matematika. Namun seiring dengan perkembangan kondisi ITK dan menyesuaikan dengan kebutuhan jaman di era big data saat ini, di rasa perlu untuk menjadikan Statistika sebagai Program Studi tersendiri yang ada di lingkungan ITK. Program Studi Statistika berada di bawah Jurusan Matematika dan Teknologi Informasi.\n" +
                "\n" +
                "Di dalam Program Studi Statistika, akan dipelajari hal-hal yang berkaitan dengan data, mulai dari  teknik mengumpulkan data, mengolah, menyajikan, menganalisis, dan menginterpretasikan hasil yang diperoleh sebagai dasar dalam pengambilan keputusan yang tepat. Selan itu, di Program Studi Statistika juga akan dipelajari metode-metode dalam memprediksi suatu kejadian di masa mendatang berdasarkan data yang tersedia, sebagai dasar pertimbangan dalam mengantisipasi hal-hal yang akan terjadi dimasa datang.\n" +
                "\n" +
                "Program Studi Statistika ITK berkomitmen untuk menghasilkan lulusan dengan kompetensi yang unggul dan terampil dalam menyelesaikan permasalahan statistik dan big data. Dalam mempersiapkan kompetensi lulusan yang sesuai dengan kebutuhan, Program Studi Statistika ITK menyusun kurikulum pendidikan sedemikian rupa untuk membekali kemampuan mahasiswa di bidang manajemen data dan komputasi. Hal ini tentunya sangat selaras dengan kebutuhan dan perkembangan jaman di era big data dan teknologi. Oleh sebab itu, lulusan dari Program Studi Statistika sangat banyak diperlukan di dunia pekerjaan, baik dari sektor pemerintah, pendidikan, bisnis, dan industri.\n" +
                "\n" +
                "Dalam proses belajar, mahasiswa akan didampingi oleh para dosen di lingkungan Program Studi Statistika dengan kualifikasi terbaik, lulusan dari Perguruan Tinggi unggul, baik di dalam maupun luar negeri, dengan predikat cumlaude (dengan pujian), sehingga sangat tidak diragukan lagi kemampuan dan kompetensinya dalam menguasai materi dan memberikan pengajaran dengan metode yang mudah dipahami oleh mahasiswa."),
                new ProdiModel("Fisika", 1, "Fisika ITK merupakan salah satu program studi yang berbasis sains dasar (basic science). Fisika ITK didirikan pada tahun 2013 bersama dengan lima program studi yang lain ketika ITK masih dalam asuhan Institut Teknologi Sepuluh Nopember (ITS) dan diresmikan sesuai dengan SK Dirjen Dikti No.65/M/Kp/III/2015. Pada tahun 2013, seluruh mahasiswa Fisika ITK dititipkan di ITS khususnya di program studi Fisika. Tepat pada bulan Agustus 2015, seluruh proses belajar mengajar Fisika dipindahkan ke Balikpapan.\n" +
                        "\n"),
                new ProdiModel("Teknik Kelautan", 14, "Pedoman pembukaan dan penutupan program studi mengacu pada SK Dirjen Dikti Nomor 108/DIKTI/Kep/2001 tentang Pedoman Pembukaan Program Studi dan/atau Jurusan Berdasarkan Keputusan Menteri Pendidikan Nasional Nomor 234/U/2000 tentang Pendirian Perguruan Tinggi. Keputusan Senat ITK tentang pembukaan program studi baru guna memenuhi kebutuhan tenaga ahli bidang teknologi serta dalam upaya pengembangan Tri Dharma Pendidikan ITK khususnya dibidang pendidikan, maka dipandang perlu membuka program studi baru. Hasil Senat ITK pada tanggal 26 Januari 2017 memutuskan dan menetapkan pembukaan program studi baru, yaitu program studi Teknik Kelautan.\n" +
                        "\n" +
                "Berdasarkan Keputusan Menteri Riset, Teknologi, dan Pendidikan Tinggi Republik Indonesia, Nomor 338/KPT/I/2017 memutuskan Keputusan Menteri Riset, Teknologi, dan Pendidikan Tinggi Republik Indonesia tentang Izin Pembukaan Program Studi Teknik Kelautan Program Sarjana pada Institut Teknologi Kalimantan di Balikpapan."),
                new ProdiModel("Teknologi Pangan", 19, "Program Studi Teknologi Pangan ITK secara resmi berdiri pada 5 April 2021 sesuai SK Menteri Pendididkan dan Kebudayaan Republik Indonesia No 89/E/O/III/2021. Teknologi Pangan ITK telah menerima mahasiswa pertamanya pada tahun 2021.  Saat ini Teknologi Pangan ITK memiliki akreditasi Baik sesuai dengan 14172/SK/BAN-PT/PB-PS/S/III/2022. Lambatnya perkembangan industri pangan di Kalimantan ditandai dengan beberapa industri saja yang mau berinvestasi di Kalimantan. Program Studi Teknologi Pangan hadir dengan harapan iklim perkembangan industri pangan di tengah rencana IKN baru menjadi lebih terarah. Banyak potensi alam Kalimantan yang belum tereksploitasi dengan sangat baik, khususnya palawija, buah tropik, dan kekayaan laut khas Kalimantan. Dengan berkembangnya Program Studi Teknologi Pangan kami bercita-cita untuk menghasilkan terobosan-terobosan baru di pengolahan pangan."),
                new ProdiModel("Teknik Perkapalan", 9, "Pendirian program studi Teknik Perkapalan bersamaan dengan pendirian Institut Teknologi Kalimantan. Pelaksanaan strategi utama dalam bidang penguatan kemampuan Sumber Daya Manusia (SDM) serta Ilmu Pengetahuan dan Teknologi (IPTEK) nasional di Koridor Ekonomi Kalimantan berada pada Masterplan Percepatan dan Perluasan Pembangunan Ekonomi Indonesia (MP3EI) 2011-2025.\n" +
                        "\n" +
                "Program studi Teknik Perkapalan memulai proses perkuliahan pada tahun 2012, sebanyak 20 mahasiswa dengan Jalur penerimaan mahasiswa melalui Seleksi Masuk ITK (SMITeK). SMITeK merupakan hasil kerjasama antara Institut Teknologi Sepuluh Nopember (ITS) Surabaya dengan Pemerintah Provinsi Kalimantan Timur (dengan beasiswa Kaltim Cemerlang). Pada tahun 2013, SMITeK membuka jalur mandiri nasional untuk calon mahasiswa yang berasal dari luar. Sedangkan pada tahun 2014 SMITek diselenggarakan melalui 2 jalur, yaitu: Seleksi Lokal Berbeasiswa Pemprov Kaltim dan Seleksi Bersama Masuk Perguruan Tinggi Negeri (SBMPTN). Pada tahun ini pula ITK diresmikan sebagai PTN oleh Presiden Susilo Bambang Yudhoyono.\n" +
                "\n" +
                "Sebelumnya program studi Teknik Perkapalan melakukan kegiatan akademik dan proses perkuliahan di kampus ITS Surabaya. Pada tahun 2015, kegiatan akademik dan proses perkuliahan dari total 31 mahasiswa dipindahkan ke Kampus ITK Karangjoang, Balikpapan. Momen ini juga sebagai penerbitan SK pendirian program studi Teknik Perkapalan ITK."),
                new ProdiModel("Rekayasa Keselamatan", 18, "Program Studi Rekayasa Keselamatan diresmikan pada tanggal 5 April 2021  SK Menteri Pendididkan dan Kebudayaan Republik Indonesia No 89/E/O/III/2021.\n" +
                        "\n" +
                "Alasan berdirinya program studi Rekayasa Keselamatan dikarenakan sampai saat ini, belum ada institusi baik negeri maupun swasta di Indonesia yang menawarkan program pendidikan sarjana Rekayasa Keselamatan. Hal ini didukung yang secara nasional jumlah kasus kecelakaan kerja mengalami peningkatan setiap tahunnya serta kebutuhan tenaga ahli keselamatan dan kesehatan kerja yang masih kurang khususnya di daerah Kalimantan. Selain itu, sebagaimana tertuang dalam rencana jangka panjang strategis nasional, ibukota negara akan dipindahkan ke Kalimantan Timur. Sehingga sebagai satu-satunya kampus teknik di Kalimantan, ITK akan menjadi mitra strategis bagi pembangunan ibukota negara baru. Tantangan lain akan muncul yaitu bagaimana lulusan-lulusan Program Studi Rekayasa Keselamatan ITK dapat menjadi kontributor aktif dalam pembangunan ibukota yang bebas dari kecelakaan kerja.\n" +
                "\n" +
                "Keunikan yang ada dalam Program Studi Rekayasa Keselamatan (PSRK) adalah adanya perkembangan keilmuan di bidang keselamatan kerja yang dulunya berfokus hanya pada personal safety, namun sejak tahun 2010 mulai berkembang pada keilmuan proses safety yang saat ini mulai menjadi perhatian perusahaan dunia dalam menjamin lingkungan yang aman. Sehingga, hal ini menjadi suatu tantangan tersendiri bagi PSRK ITK untuk menjawab lulusan-lulusan seperti apa kemudian yang dibutuhkan terutama bagi perusahaan-perusahaan di Kalimantan dalam melakukan rekayasa keselamatan untuk menciptakan zero accident. Sehingga prodi Rekayasa Keselamatan ITK memposisikan diri untuk fokus pada konsep process safety  dalam rangka pengendalian resiko yang ada dilingkungan kerja serta memberikan skill dan pengetahuan yang penting dalam melakukan persiapan, pelaksanaan, monitoring dan evaluasi serta peningkatan sistem manajemen keselamatan dan kesehatan kerja. "),
                new ProdiModel("Teknik Elektro", 4, "Prodi Teknik Elektro Berdiri pada 14 Februari 2014 yang diusulkan oleh Jurusan Teknik Elektro Institut Teknologi Sepuluh Nopember (ITS) . Prodi teknik elektro diinisiasi untuk menghasilkan SDM dalam bidang teknik untuk memenuhi kebutuhan industri yang ada di Kalimantan Timur. Program Studi Teknik Elektro ITK menerima angkatan pertama sebanyak 20 mahasiswa. Jalur penerimaan mahasiswa ITK melalui Jalur Seleksi Masuk ITK (SMITeK) yang merupakan hasil kerjasama Institut Teknologi Sepuluh Nopember (ITS) Surabaya dengan Pemerintah Provinsi Kalimantan Timur, melalui beasiswa Kaltim Cemerlang. Proses kuliah pada awal inisiasi diadakan di Institut Teknologi Sepuluh Nopember sembari menunggu persiapan pembangunan gedung."),
                new ProdiModel("Teknik Industri", 12, "Prodi Studi Teknik Industri dibuka berdasarkan hasil keputusan Senat ITK pada tanggal 26 Januari 2017 yang berisi tentang pembukaan program studi baru guna memenuhi kebutuhan tenaga ahli bidang teknologi serta dalam upaya pengembangan Tri Dharma Pendidikan ITK khususnya dibidang pendidikan, maka dipandang perlu membuka program studi baru. Sehingga disusunlah pembukaan program studi teknik industri yang mengacu pada SK Dirjen Dikti Nomor 108/DIKTI/Kep/2001 tentang Pedoman Pembukaan Program Studi dan/atau Jurusan Berdasarkan Keputusan Menteri Pendidikan Nasional Nomor 234/U/2000 tentang Pendirian Perguruan Tinggi serta melibatkan pakar Teknik Industri seperti Dr. Ir. Sri Gunani Pratiwi (ITS), Ir. Sritomo Wignjosoebroto, M.Sc (ITS) dan Prof. Ir. Budi Santosa, MS, PhD (ITS) agar memperoleh masukan terkait kondisi terkini dibidang Teknik Industri.\n" +
                        "\n" +
                "Berdasarkan Surat Keputusan Menteri Riset, Teknologi, dan Pendidikan Tinggi Repoblik Indonesia No.209/KPT/I/2017, tanggal 4 April 2017 tentang izin pembukaan Program Studi Teknik Indsutri Program Sarjana pada Institut Teknologi Kalimantan."),
                new ProdiModel("Teknik Kimia", 5, "Teknik kimia merupakan program studi yang mempelajari pemrosesan bahan mentah menjadi produk yang bernilai tambah, baik produk jadi maupun produk setengah jadi dengan menerapkan prinsip kimia, fisika, biologi dengan memperhatikan faktor keamanan, lingkungan dan ekonomis.\n" +
                        "\n" +
                "Program Studi Teknik Kimia (PSTK) ITK sendiri resmi didirikan pada tahun 2015 sesuai SK Menteri Riset, Teknolgi, dan Pendidikan Tiggi no 65/M/Kp/III/2015.bersama 4 (empat) prodi pertama ITK lainnya. Hanya saja PSTK telah menerima mahasiswa pertamanya pada tahun 2012 dimana seluruh kegiatan perkuliahan dilaksanakan di Jurusan Teknik Kimia ITS, kampus yang ditunjuk oleh Kementerian Ristekdikti sebagai Pelaksana pendirian ITK. Pendirian ITK dan PSTK ini diharapkan mamapu menjawab tantangan pengembangan SDM di Indonesia Timur khususnya sehingga mampu berkontribusi aktif dalam perkembangan dan pembangunan daerah khususnya di Kalimantan."),
                new ProdiModel("Teknik Logistik", 21, "Teknik Logistik merupakan program studi yang mempelajari tentang cara untuk mengatur dan mengontrol arus barang, energi, informasi, dan sumber daya lainnya dari titik supply ke titik konsumsi dengan tujuan mengoptimalkan dan mengefisiensikan penggunaan modal. Logistik juga mencakup integrasi informasi (smart logistic), pergudangan, reverse logistics dan pemaketan.\n" +
                        "\n" +
                "Program Studi Teknik Logistik ITK sendiri resmi didirikan pada tahun 2021 sesuai SK Menteri Pendidikan, Kebudayaan, Riset, dan Teknologi Direktorat Jenderal Pendidikan Tinggi nomor 6320/E1/TP.01.06/2021 seusai proses seleksi mandiri di ITK telah ditutup. Sehingga proses penerimaan mahasiswa baru Teknik Logistik baru akan dibuka pada tahun 2022 mengikuti proses seleksi SNMPTN, SBMPTN, dan jalur Mandiri (Summit ITK). Pendirian Program Studi Teknik Logistik ini diharapkan mampu menjawab tantangan pengembangan SDM di Indonesia Timur khususnya sehingga mampu berkontribusi aktif dalam perkembangan dan pembangunan daerah khususnya di Kalimantan."),
                new ProdiModel("Teknik Mesin", 3, "Program Studi Teknik Mesin merupakan salah satu program studi tertua di ITK. Program Studi Teknik Mesin ITK didirikan pada tahun 2012 dengan jumlah mahasiswa sebanyak 20 mahasiswa yang berasal dari Kalimantan. Jalur penerimaan mahasiswa ITK pada saat itu dilakukan melalui Seleksi Masuk ITK (SMITeK) yang merupakan hasil kerjasama antara ITS dan Pemprov Kaltim. Seluruh mahasiswa berasal dari Provinsi Kaltim mendapatkan beasiswa Kaltim Cemerlang.  Kegiatan perkuliaahan pada tahun pertama sampai tahun ketiga dilaksanakan di kampus ITS. Pada tahun 2015 semua kegiatan akademik dan non akademik sudah dilaksanakan di kampus ITK di Karang Joang Balikpapan. Untuk mencetak lulusan Teknik Mesin ITK yang berkualitas, telah disusun kurikulum pengajaran yang memberikan dasar ilmu pengetahuan dan teknik yang kuat serta implementasi dalam bidang keteknikan sehingga lulusan Teknik Mesin ITK juga harus mampu bersaing di dunia kerja."),
                new ProdiModel("Arsitektur",15, "Institut Teknologi Kalimantan (ITK) merupakan perguruan tinggi yang fokus dalam bidang teknologi untuk menunjang kebutuhan dunia industri. ITK memulai proses perkuliahan pada tahun 2012 dan menerima mahasiswa angkatan pertama sebanyak 100 mahasiswa. 5 program studi awal saat ITK berdiri yaitu: Teknik Elektro, Teknik Mesin, Teknik Perkapalan, Teknik Kimia dan Teknik Sipil. Jalur penerimaan mahasiswa ITK tersebut dilakukan melalui Seleksi Masuk ITK (SMITeK) yang merupakan hasil kerjasama antara Institut Teknologi Sepuluh Nopember (ITS) Surabaya dengan Pemerintah Propinsi Kalimantan Timur, melalui beasiswa Kaltim Cemerlang. Pada tahun 2013, ITK menyelenggarakan SMITeK dengan membuka jalur mandiri nasional untuk calon mahasiswa yang berasal dari luar Kaltim. Selain itu, juga dibuka lima program studi baru, yaitu program studi Teknik Material dan Metalurgi, Fisika, Matematika, Sistem Informasi, dan Perencanaan Wilayah dan Kota. SMITek pada tahun 2014 diselenggarakan melalui 2 jalur, yaitu Seleksi Lokal Berbeasiswa Pemprov Kaltim dan Seleksi Bersama Masuk Perguruan Tinggi Negeri (SBMPTN). Pada tahun ini pula ITK diresmikan sebagai PTN oleh Presiden Susilo Bambang Yudhoyono. Dari tahun 2012 sampai dengan tahun 2014, ITK memiliki total mahasiswa sebanyak 263 mahasiswa yang melakukan kegiatan akademik dan proses perkuliahan di kampus ITS Surabaya. Pada tahun 2015, kegiatan akademik dan proses perkuliahan dipindahkan di Kampus ITK Karangjoang, Balikpapan."),
                new ProdiModel("Desain Komunikasi Visual",22, "Program Studi Desain Komunikasi Visual didirikan pada tahun 2022 dengan NOMOR : 4653/SK/BAN-PT/Ak.P/S/VII/2022 sebagai salah satu Program Studi di Institut Teknologi Kalimantan sebagai salah satu program studi di bawah Jurusan Teknik Sipil Dan Perencanaan. Koordinator Program Studi pertama adalah Olivia Febrianty Ngabito M.Sn. Jumlah Dosen dari DKV Berjumlah 9 Orang. Program Studi Desain Komunikasi Visual di Institut Teknologi Kalimantan Merupakan Jurusan Desain Komunikasi Visual pertama di pulau Kalimantan. Hal ini merespon dari berkembangnya industri desain di kalimantan terutama Kota Balikpapan dengan Konsep Smart City."),
                new ProdiModel("Perencanaan Wilayah dan Kota",8, "Institut Teknologi Kalimantan memulai proses perkuliahan pada tahun 2012. Pada tahun tersebut, ITK menerima mahasiswa angkatan pertama sebanyak 100 mahasiswa dan didistribusikan ke 5 program studi awal ITK, yaitu: Teknik Elektro, Teknik Mesin, Teknik Perkapalan, Teknik Kimia dan Teknik Sipil. Jalur penerimaan mahasiswa ITK tersebut dilakukan melalui Seleksi Masuk ITK (SMITeK) yang merupakan hasil kerjasama antara Institut Teknologi Sepuluh Nopember (ITS) Surabaya dengan Pemerintah Propinsi Kalimantan Timur, melalui beasiswa Kaltim Cemerlang.\n" +
                "\n" +
                "Permasalahan tata ruang (spasial) yang semakin dinamis disamping tuntutan akan pembangunan ekonomi yang berkelanjutan meningkatkan kebutuhan akan sarjana unggul bidang perencanaan wilayah dan kota. Oleh karena itu, Institut Teknologi Kalimantan membuka Program Studi Perencanaan Wilayah dan Kota (PWK) mulai tahun 2013. Melalui jalur SMITek dengan membuka jalur mandiri nasional untuk calon mahasiswa baru, ITK menerima mahasiswa Prodi PWK bersamaan dengan 4 prodi lainnya yang baru dibuka seperti Teknik Material dan Metalurgi, Fisika, Matematika, dan Sistem Informasi. Program studi ini menfokuskan diri pada studi perencanaan, perancangan, pemanfaatan, pengelolaan, dan pengendalian ruang kota, wilayah, dan pesisir yang terpadu. Pada tahun 2013, PWK mendapatkan 12 mahasiswa yang merupakan putra-putri Kalimantan Timur dengan didukung oleh beasiswa Kaltim Cemerlang.\n" +
                "\n" +
                "Pada tahun 2014, SMITeK diselenggarakan lagi melalui 2 jalur, yaitu Seleksi Lokal Berbeasiswa Pemprov Kaltim Cemerlang dan Seleksi Bersama Masuk Perguruan Tinggi Negeri (SBMPTN). Pada tahun ini pula ITK diresmikan sebagai PTN oleh Presiden Susilo Bambang Yudhoyono. Dari tahun 2012 sampai dengan tahun 2014, ITK memiliki total mahasiswa sebanyak 263 mahasiswa yang melakukan kegiatan akademik dan proses perkuliahan di kampus ITS Surabaya. Pada tahun 2015, kegiatan akademik dan proses perkuliahan dipindahkan ke Kampus ITK Karang Joang, Balikpapan."),
                new ProdiModel("Teknik Sipil",7, "Program Studi S1 Teknik Sipil Jurusan Teknik Sipil dan Perencanaan Institut Teknologi Kalimantan lahir bersama-sama dengan pendirian Institut Teknologi Kalimantan. Riwayat pendirian Institut Teknologi Kalimantan didasarkan pada pelaksanaan strategi utama dalam bidang kemampuan Sumber Daya Manusia (SDM) serta Ilmu Pengetahuan dan Teknologi (IPTEK) nasional di Koridor Ekonomi Kalimantan semagaimana yang disusun dalam Masterplan Percepatan dan Perluasan Pembangunan Ekonomi Indonesia (MP3EI) 2011-2025. Selain Politeknik, hingga tahun 2012 Kalimantan Timur hanya memiliki satu universitas negeri yaitu Universitas Mulawarman yang berada di Samarinda. Menginat kekayaan Sumber Daya Alam (SDA) dan pertambahan penduduk yang terus meningkat, maka penambahan Perguruan Tinggi Negeri (PTN) sangat diperlukan utuk mendukung perkembangan dan pembangunan daerah khusunya Kalimantan.\n" +
                "\n" +
                "Program Studi Teknik Sipil ITK didirikan bersama 4 program studi lain yakni Teknik Elektro, Teknik Mesin, Teknik Perkapalan, dan Teknik Kimia yang merupakan program studi rintisan. Program Studi Teknik Sipil ITK memulai perkuliahan sejak awal berdiri hingga tahun 2014 di kampus ITS Surabaya. Pada tahun 2015 kegiatan akademik dan proses perkuliahan dipindahkan di Kampus ITK Karang Joang, Balikpapan."),
                new ProdiModel("Teknik Lingkungan",13, "Program Studi Teknik Lingkungan merupakan program studi ke-13 yang berdiri di Institut Teknologi Kalimantan. Proses pendirian Program Studi Teknik Lingkungan dibantu oleh Dosen Program Studi Teknik Sipil di bawah arahan Dr. Ir. Elina Sitepu Pandebesie, M.T., yang kemudian dilanjutkan oleh 5 orang Dosen Program Studi Teknik Lingkungan yang diterima di ITK pada Januari 2016. Pengajuan program studi ini telah dilakukan sejak bulan Maret 2016, sebelum akhirnya resmi terbentuk dengan ditandai penerbitan Keputusan Menteri Riset, Teknologi, dan Pendidikan Tinggi RI Nomor 285/KPT/I/2017 Tentang Izin Pembukaan Program Studi Teknik Lingkungan Program Sarjana pada Institut Teknologi Kalimantan pada tanggal 29 Mei 2017. Dengan terbitnya izin pendirian prodi, Program Studi Teknik Lingkungan melakukan proses penjaringan mahasiswa melalui Seleksi Mandiri tahun 2017. Melalui seleksi tersebut, secara resmi 10 mahasiswa angkatan pertama diterima pada Program Studi ini dibawah arahan Koordinator Program Studi Teknik Lingkungan periode Juni – Agustus 2018, M. Ma’arij Harfadli, S.T., M.T. Selanjutnya sejak September 2018 hingga saat ini, posisi Koordinator Program Studi Teknik Lingkungan dipegang oleh Umi Sholikah, S.Si., M.T."),
                new ProdiModel("Teknik Material dan Metalurgi",6, "Program Studi Teknik Material dan Metalurgi didirikan pada tahun 2013 sebagai salah satu Program Studi di Institut Teknologi Kalimantan sebagai salah satu program studi di bawah Jurusan Ilmu Kebumian dan Lingkungan. Koordinator Program Studi pertama adalah Yunita Triana, S.Si. M.Si dengan jumlah mahasiswa angkatan 2013 sebanyak 11 orang. Namun, kegiatan akademik belum berjalan optimal karena gedung perkuliahan di Balikpapan masih dalam masa pembangunan, keterbatasan pengajar di bidang Material dan Metalurgi dan fasilitas laboraturium, sehingga pada saat itu mahasiswa dititipkan di Institut Teknologi Sepuluh Nopember (ITS) hingga tahun 2015. Secara resmi, Program Studi Teknik Material dan Metalurgi memiliki izin pendirian berdasarkan SK Dirjen Dikti 65/M/Kp/III/2015 tertanggal 20 Maret 2015 yang ditandatangani oleh Bapak Patdono Suwignjo. Hingga tahun 2018, Perkembangan jumlah penerimaan mahasiswa pada tahun 2014 sebanyak 9 orang, angkatan tahun 2015 sebanyak 46, angkatan 2016 sebanyak 79, angkatan 2017 sebanyak 82 orang, dan 2018 sebanyak 86 orang. Sejak saat itu, kegiatan belajar mengajar berjalan secara kontinu dan konsisten dengan jumlah rata-rata mahasiswa baru sebesar 80 orang. Pada tahun 2018 Teknik Material dan Metalurgi terakreditasi B berdasarkan keputusan BAN-PT No.859/K/BAN-PT/ Akred/S/III/2018.")
        );

        for (int i = 0; i < buttons.size(); i++) {
            setProdiButton(buttons.get(i), prodiModels.get(i));
        }
    }

    private void setProdiButton(Button namaButton, ProdiModel prodi) {
        namaButton.setText(prodi.getNama());
        namaButton.setUserData(prodi);
        namaButton.setOnAction(this::showProdiInformation);
    }

    private void showProdiInformation(ActionEvent event) {
        if (event.getSource() instanceof Button clickedButton) {
            ProdiModel prodi = (ProdiModel) clickedButton.getUserData();

            paneContainer.getChildren().get(0).setVisible(false);
            headingLabel.setVisible(false);
            badges.setVisible(false);
            backButton.setVisible(true);
            prodiInformationPane.setVisible(true);
            namaProdiLabel.setText(prodi.getNama());
            nomorProdiLabel.setText("Nomor Prodi : " + prodi.getNomorProdi());
            deskripsiProdiLabel.setText(prodi.getDeskripsi());
            imageProdi.getStyleClass().add(clickedButton.getGraphic().getStyleClass().get(clickedButton.getGraphic().getStyleClass().size() - 1));
        }
    }

    @FXML
    private void hideProdiInformation() {

        paneContainer.getChildren().get(0).setVisible(true);
        headingLabel.setVisible(true);
        badges.setVisible(false);
        prodiInformationPane.setVisible(false);
        backButton.setVisible(false);
        imageProdi.getStyleClass().removeLast();


    }
}


